
import modelo.Elemento;
import modelo.ListaRank;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class ResultadoRank extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoRank
     */
    public ResultadoRank() {
        initComponents();
        popularCampos();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        votosPosicaoUm = new javax.swing.JLabel();
        votosPosicaoDois = new javax.swing.JLabel();
        votosPosicaoTres = new javax.swing.JLabel();
        criarNovoRank = new javax.swing.JButton();
        votarNovamente = new javax.swing.JButton();
        primeiraPosicao = new javax.swing.JLabel();
        segundaPosicao = new javax.swing.JLabel();
        terceiraPosicao = new javax.swing.JLabel();
        tituloResultadoRank = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Overview Rank");
        setSize(new java.awt.Dimension(500, 460));

        votosPosicaoUm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        votosPosicaoUm.setText("00");

        votosPosicaoDois.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        votosPosicaoDois.setText("00");

        votosPosicaoTres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        votosPosicaoTres.setText("00");

        criarNovoRank.setText("Novo Rank");
        criarNovoRank.setPreferredSize(new java.awt.Dimension(180, 40));
        criarNovoRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarNovoRankActionPerformed(evt);
            }
        });

        votarNovamente.setText("Votação");
        votarNovamente.setPreferredSize(new java.awt.Dimension(180, 40));
        votarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votarNovamenteActionPerformed(evt);
            }
        });

        primeiraPosicao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        primeiraPosicao.setText("AAAAAAAAAAAAAAAAAAA");

        segundaPosicao.setText("AAAAAAAAAAAAAAAAAAA");

        terceiraPosicao.setText("AAAAAAAAAAAAAAAAAAA");

        tituloResultadoRank.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tituloResultadoRank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloResultadoRank.setText("jLabel1");
        tituloResultadoRank.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloResultadoRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terceiraPosicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(segundaPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(primeiraPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(votosPosicaoUm)
                            .addComponent(votosPosicaoDois)
                            .addComponent(votosPosicaoTres)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(criarNovoRank, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(votarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloResultadoRank, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(primeiraPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosPosicaoUm))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(segundaPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosPosicaoDois))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(terceiraPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosPosicaoTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(votarNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(criarNovoRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        setSize(new java.awt.Dimension(500, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void criarNovoRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarNovoRankActionPerformed
        new CreateRank().setVisible(true);
        ResultadoRank.this.dispose();
    }//GEN-LAST:event_criarNovoRankActionPerformed

    private void votarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votarNovamenteActionPerformed
        new TelaVoto().setVisible(true);
        ResultadoRank.this.dispose();
    }//GEN-LAST:event_votarNovamenteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Logado().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void popularCampos() {

        Elemento primeiraPosicao = ListaRank.getPosicaoUm();
        Elemento segundaPosicao = ListaRank.getPosicaoDois();
        Elemento terceiraPosicao = ListaRank.getPosicaoTres();
        String tituloResultadoRank = ListaRank.getPosicaoTitulo();

        this.primeiraPosicao.setText(primeiraPosicao.getNome());
        this.segundaPosicao.setText(segundaPosicao.getNome());
        this.terceiraPosicao.setText(terceiraPosicao.getNome());
        this.tituloResultadoRank.setText(tituloResultadoRank);
        this.votosPosicaoUm.setText(String.valueOf(primeiraPosicao.getQuantidadeVotos()));
        this.votosPosicaoDois.setText(String.valueOf(segundaPosicao.getQuantidadeVotos()));
        this.votosPosicaoTres.setText(String.valueOf(terceiraPosicao.getQuantidadeVotos()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoRank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoRank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoRank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoRank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoRank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarNovoRank;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel primeiraPosicao;
    private javax.swing.JLabel segundaPosicao;
    private javax.swing.JLabel terceiraPosicao;
    private javax.swing.JLabel tituloResultadoRank;
    private javax.swing.JButton votarNovamente;
    private javax.swing.JLabel votosPosicaoDois;
    private javax.swing.JLabel votosPosicaoTres;
    private javax.swing.JLabel votosPosicaoUm;
    // End of variables declaration//GEN-END:variables
}
