
import modelo.Elemento;
import modelo.ListaRank;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fábio
 */
public class TelaVoto extends javax.swing.JFrame {

    public TelaVoto() {
        initComponents();
        popularCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verRank = new javax.swing.JButton();
        telaVotoPosicaoUm = new javax.swing.JButton();
        telaVotoPosicaoDois = new javax.swing.JButton();
        telaVotoPosicaoTres = new javax.swing.JButton();
        telaVotoTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking");
        setPreferredSize(new java.awt.Dimension(400, 420));
        setSize(new java.awt.Dimension(472, 514));

        verRank.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verRank.setText("Ver Rank");
        verRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRankActionPerformed(evt);
            }
        });

        telaVotoPosicaoUm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        telaVotoPosicaoUm.setText("Botão Voto Um");
        telaVotoPosicaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaVotoPosicaoUmActionPerformed(evt);
            }
        });

        telaVotoPosicaoDois.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        telaVotoPosicaoDois.setText("Botão Voto Dois");
        telaVotoPosicaoDois.setMaximumSize(new java.awt.Dimension(300, 35));
        telaVotoPosicaoDois.setMinimumSize(new java.awt.Dimension(300, 35));
        telaVotoPosicaoDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaVotoPosicaoDoisActionPerformed(evt);
            }
        });

        telaVotoPosicaoTres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        telaVotoPosicaoTres.setText("Botão Voto Tres");
        telaVotoPosicaoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaVotoPosicaoTresActionPerformed(evt);
            }
        });

        telaVotoTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        telaVotoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telaVotoTitulo.setText("Label Titulo ");
        telaVotoTitulo.setMaximumSize(new java.awt.Dimension(464, 54));
        telaVotoTitulo.setMinimumSize(new java.awt.Dimension(464, 54));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(verRank, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telaVotoPosicaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(telaVotoPosicaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(telaVotoPosicaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 96, Short.MAX_VALUE))
            .addComponent(telaVotoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(telaVotoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(telaVotoPosicaoUm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(telaVotoPosicaoDois, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(telaVotoPosicaoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(verRank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(494, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRankActionPerformed
        new ResultadoRank().setVisible(true);
        TelaVoto.this.dispose();
    }//GEN-LAST:event_verRankActionPerformed

    private void telaVotoPosicaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaVotoPosicaoUmActionPerformed
        String votoPosicaoUm = telaVotoPosicaoUm.getText();
        Elemento elementoVotado = ListaRank.getListaPosicaoUm().stream().filter(elemento -> votoPosicaoUm.equals(elemento.getNome())).findAny().orElse(null);
        elementoVotado.receberVotos();
        new ResultadoRank().setVisible(true);
        TelaVoto.this.dispose();
    }//GEN-LAST:event_telaVotoPosicaoUmActionPerformed

    private void telaVotoPosicaoDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaVotoPosicaoDoisActionPerformed

        String votoPosicaoDois = telaVotoPosicaoDois.getText();
        Elemento elementoVotado = ListaRank.getListaPosicaoDois().stream().filter(elemento -> votoPosicaoDois.equals(elemento.getNome())).findAny().orElse(null);
        elementoVotado.receberVotos();
        new ResultadoRank().setVisible(true);
        TelaVoto.this.dispose();
    }//GEN-LAST:event_telaVotoPosicaoDoisActionPerformed

    private void telaVotoPosicaoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaVotoPosicaoTresActionPerformed

        String votoPosicaoTres = telaVotoPosicaoTres.getText();
        Elemento elementoVotado = ListaRank.getListaPosicaoTres().stream().filter (elemento -> votoPosicaoTres.equals(elemento.getNome())).findAny().orElse(null);
        elementoVotado.receberVotos();
        new ResultadoRank().setVisible(true);
        TelaVoto.this.dispose();
    }//GEN-LAST:event_telaVotoPosicaoTresActionPerformed

    private void popularCampos() {

        Elemento posicaoUm = ListaRank.getPosicaoUm();
        Elemento posicaoDois = ListaRank.getPosicaoDois();
        Elemento posicaoTres = ListaRank.getPosicaoTres();
        String posicaoTitulo = ListaRank.getPosicaoTitulo();

        this.telaVotoPosicaoUm.setText(posicaoUm.getNome());
        this.telaVotoPosicaoDois.setText(posicaoDois.getNome());
        this.telaVotoPosicaoTres.setText(posicaoTres.getNome());
        this.telaVotoTitulo.setText(posicaoTitulo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaVoto().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton telaVotoPosicaoDois;
    private javax.swing.JButton telaVotoPosicaoTres;
    private javax.swing.JButton telaVotoPosicaoUm;
    private javax.swing.JLabel telaVotoTitulo;
    private javax.swing.JButton verRank;
    // End of variables declaration//GEN-END:variables
}
